Missing Header in Sample File
ONSdigital/census-rm-sample-loader pull request #11
Opened 2019-07-15 10:47 UTC by NickGrantONS

# Motivation and Context
Defect where generated sample file was missing header.

# What has changed
Added header.

# How to test?
Generate the sample. Load the sample.

# Links
Trello: https://trello.com/c/MTf2ef1f

2019-07-15 10:48 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEFECT: Generated sample missing header](https://trello.com/c/MTf2ef1f/961-defect-generated-sample-missing-header)

2019-07-15 11:14 UTC, jcox-dev requested changes
Might be time to just do this "properly" with the csv standard library.

[Example using DictWriter](https://docs.python.org/3/library/csv.html#csv.DictWriter) might be the way to go.

2019-07-16 13:06 UTC, rjweeks approved these changes

2019-07-17 09:02 UTC, NickGrantONS commented
agree that Dictwriter/CSV thing would be better, but a bit much to fix the defect

2019-07-17 09:07 UTC, jcox-dev approved these changes

2019-07-17 10:12 UTC, merged