Automate census docker build
ONSdigital/census-rm-sample-loader pull request #2
Opened 2019-02-08 12:29 UTC by AdeHarrison

2019-02-08 13:25 UTC, AdamHawtin approved these changes

2019-02-14 08:53 UTC, davidmort requested changes

2019-02-14 08:53 UTC, davidmort commented on .travis.yml
> +    - rm-census
this can be master branch as this is a census repo

2019-02-14 08:54 UTC, davidmort requested changes

2019-02-14 08:54 UTC, davidmort commented on .travis.yml
> +- if [ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
this can be master branch as this is a census repo

2019-02-14 11:39 UTC, AdamHawtin requested changes
The PR is still targeting rm-census branch, should be master.

2019-02-14 11:44 UTC, merged