Load sample flag to return sample units
ONSdigital/census-rm-sample-loader pull request #22
Opened 2020-02-25 15:46 UTC by LukeLoze1

During Performance Tests of 30 million (would have been the same for real run) the sample_load fails as it stores all loaded samples in memory and returns them.

This has added a flag to load_sample_file store_loaded_sample_units that is defaulted to False.  If this is True then they will be stored in memory and then returned (for ATs) if not then they won't be stored in memory and large scale Perf Tests will be unlocked

To Test:
    There is a new unit test that 'proves' it.  There are updates to Perf and ATs on this ticket that will bring in the new release v1.0.1.  If you wish to test them with this branch change their pipefile to census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader", ref = "load-sample-flag-to-return-sample-units”}, then pipenv install --dev

Link:
  https://trello.com/c/luQsADkR/640-enhance-sampleloader-script-8

2020-02-25 17:02 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-02-26 09:48 UTC, NickGrantONS commented on load_sample.py
> +                    f'sampleunit:{sample_unit_id}': _create_sample_unit_json(sample_unit_id, sample_row)}
you know this isn't JSON, right? I don't really understand why (or how) it works like this.

2020-02-26 09:50 UTC, NickGrantX requested changes
Minor comment, but it works so I'll probably just approve it. Just seems really odd to have a colon in the middle of a JSON element name

2020-02-26 10:26 UTC, NickGrantX approved these changes
Sod it. I'm approving. I might not understand the legacy stuff, but it's not your job to fix/tinker.

2020-02-26 10:32 UTC, merged