771 make sample load changes to meet new sample spec
ONSdigital/census-rm-sample-loader pull request #26
Opened 2020-03-31 13:28 UTC by ryangrundy7

Updated the sample loader to match the sample frame spec. I've removed arids and added print_batch and estab_uprn.

## Test
- generate sample and validate it
- Try and load the sample into the database
- Run with other prs 

[trello](https://trello.com/c/zm2Ssvnn/771-make-sample-load-changes-to-meet-new-sample-spec-13)

2020-03-31 13:28 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make sample load changes to meet new sample spec (13)](https://trello.com/c/zm2Ssvnn/771-make-sample-load-changes-to-meet-new-sample-spec-13)

2020-04-01 10:59 UTC, NickGrantX approved these changes
ATs passing. LGTM 👍

2020-04-02 07:32 UTC, AdamHawtin requested changes

2020-04-02 07:32 UTC, AdamHawtin commented on validate_sample.py
> +            'UPRN': [mandatory(), max_length(12), numeric(), unique()],
Are we sure it's valid to make UPRN `unique`? I don't think this is correct, rows like CE units can have the same UPRN.

2020-04-02 07:39 UTC, AdamHawtin commented on tests/test_validate_sample.py
> +    def test_validate_sample_duplicate_uprns(self):
Same comment re `unique` UPRN's

2020-04-02 08:13 UTC, AdamHawtin approved these changes
👍 LGTM

2020-04-03 08:02 UTC, merged