Check for whitspace in CSV file
ONSdigital/census-rm-sample-loader pull request #29
Opened 2020-04-14 15:00 UTC by LeoKHoward

# Motivation and Context
DR has noticed that some fields in sample files should be blank but actually contain whitespace which could cause issues further down the line if recognised as a value

# What has changed
Added in a new validator to check if field starts with a whitespace
Created unit test for happy and unhappy path

# How to test?
Edit a test sample in the repo by adding in blank spaces where the field is expected to be blank
Then run `pipenv run python validate_sample.py <sample_file>`
Validation error should come up specifying which row/column

# Links
https://trello.com/c/yUU8RM7J/830-add-white-space-check-to-sample-load-validator-3

2020-04-14 15:06 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add white space check to sample load validator (3)](https://trello.com/c/yUU8RM7J/830-add-white-space-check-to-sample-load-validator-3)

2020-04-14 15:21 UTC, NickGrantONS commented on validators.py
> +        if value.startswith(" "):
I'm not sure if `startsWith` qualifies as "contains whitespace". I think we should compare the original with the `.strip()` result if you want to know whether there was whitespace at the beginning or the end of the value.

You can use `value.replace(" ", "") == ''` to check to see if a value is _entirely_ whitespace.

2020-04-14 15:22 UTC, NickGrantX requested changes
See comments

2020-04-14 15:36 UTC, NickGrantX approved these changes
LGTM 👍

2020-04-15 07:56 UTC, hbrace approved these changes

2020-04-15 08:00 UTC, merged