Update Validators
ONSdigital/census-rm-sample-loader pull request #36
Opened 2020-08-18 08:52 UTC by LeoKHoward

# Motivation and Context
Confluence updated with more detailed validation/rules and took opportunity to fine tune current validation where possible

# What has changed
Postcode validator
Pipe character validator
CE E validator with two treatment code exceptions
Tests

# How to test?
Run make test
Validate a sample file

# Links
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CRM&title=Address+Frame+specification+2021
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?spaceKey=CRM&title=ESTAB_TYPES+2021
https://trello.com/c/MmDZrIjk/1245-update-validation-on-sample-load-and-bulk-new-address-8

2020-08-18 08:54 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update validation on sample load and bulk new address (8)](https://trello.com/c/MmDZrIjk/1245-update-validation-on-sample-load-and-bulk-new-address-8)

2020-08-18 09:14 UTC, AdamHawtin submitted a review, later dismissed

2020-08-18 09:14 UTC, AdamHawtin commented on validators.py
> +def no_padding_whitespace_and_no_pipe_character():
I think these should be separate validators, like this if a value had padding whitespace and a pipe, the pipe won't be spotted.

Also the check for the pipe will be relatively slow over lots of rows, we can be savvy with which columns we apply it too (e.g. column that uses the `in_set` or `numeric` validator doesn't need to also check for the pipe explicitly).

2020-08-18 12:37 UTC, NickGrantX requested changes
Things I've found (repeated on both cards, because they have the code duplicated):
- Estab type doesn't need a max - already restricted to set
- Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch is 58 characters, but town name is max 30
- Lat/long should be between -180.0 to +180.0 (in fact probably not more than 14 degrees West to be honest... etc see https://en.wikipedia.org/wiki/List_of_extreme_points_of_the_United_Kingdom#:~:text=Westernmost%20point%20%E2%80%93%20Rockall%20at%2057,W%20is%20the%20westernmost%20point.)
- HTC_WILLINGNESS, HTC_DIGITAL, TREATMENT_CODE - don't check for padding or whitespace, because already restricted to set

2020-08-19 06:41 UTC, NickGrantONS commented on validate_sample.py
> +            'ESTAB_TYPE': [mandatory(), in_set(self.ESTAB_TYPES), no_padding_whitespace()],
doesn't need to check for padding/whitespace because it already has an `in_set` check

2020-08-19 06:41 UTC, NickGrantONS commented on validate_sample.py
>              'ADDRESS_LEVEL': [mandatory(), in_set({'E', 'U'}), no_padding_whitespace()],
doesn't need to check for padding/whitespace because it already has an `in_set` check

2020-08-19 06:44 UTC, NickGrantONS requested changes
`latitude_longitude` still doesn't check to see if the location is on the planet, at least, which is done by simply checking value is within range -180 to 180

2020-08-19 09:51 UTC, NickGrantONS approved these changes
I would have done lat-long validation in a single validator function, but no reason to block the PR

2020-08-20 06:23 UTC, AdamHawtin commented on validators.py
> +        if not -180 <= float(value) <= 180:
This needs to catch a `ValueError` and raise it as an `Invalid`, as is if the value can't be converted to float it kills the script.

2020-08-21 10:42 UTC, ryangrundy7 approved these changes

2020-08-21 11:41 UTC, merged